### ISSUE TITLE
issue trying to grab local key

### ISSUE THREAD

**Issue by UlTriX** [mitchellrj/eufy_robovac#10]
Hi,

I am having trouble setting up more specifically getting the local jey.

I have robovac 30C Firmware 1.1.3 Wi-Fi version and 1.1.4 MCU version 

using adb logcat | grep -e 'tuya.m.my.group.device.list' to grad the devide ID and localKey
although the devId was quite easy to grab the localkey not so much.

The only 16 digit hex I see in the output json is the UceA1fpIZIAySN6U

Is there anything I am missing?

**Comment by pabsi** [comment]
See https://github.com/mitchellrj/eufy_robovac/issues/1

**Comment by UlTriX** [comment]
Thank you.

Apologies for not closing the issue.

I end up grabbing the localKey.

My issue was due to the robovac being shared with me and I was not the original user that linked the robovac.

Maybe a note should be added regarding this scenario.
